sequenceDiagram
participant browser
participant server

    browser->>server: Browser does POST request to server adress new_note
    activate server
    server-->>browser: Server respondes with URL redirect for browser to submit new GET request.
    deactivate server

    browser->>server: Browser does GET request of adress notes. This causes 3 more HTTP request in order: main.css, main.js and data.json
    activate server
    server-->>browser: Server respondes with the updated files. 
    deactivate server

